version: '3'
services:
    laravel.test:
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mariadb
            - redis
            - memcached
            - meilisearch
#            - minio
            - mailpit
#            - selenium
            - soketi
#            - cassandra
            - mongodb
#    cassandra:
#        image: cassandra:4
#        networks:
#            - sail
#        volumes:
#            - ./data:/var/lib/cassandra/data
#        ports:
#            - '${FORWARD_CASSANDRA_PORT:-7000}:7000'
#            - '${FORWARD_CASSANDRA_PORT:-7001}:7001'
#            - '${FORWARD_CASSANDRA_PORT:-9042}:9042'
#            - '${FORWARD_CASSANDRA_PORT:-7199}:7199'
#            - '${FORWARD_CASSANDRA_PORT:-9160}:9160'
#        environment:
#            CASSANDRA_CLUSTER_NAME: cloudinfra
#            CASSANDRA_SEEDS: cassandra
    mongodb:
        image: mongo
        networks:
            - sail
        ports:
            - '${FORWARD_MONGODB_PORT:-27017}:27017'
        volumes:
            - mongo-data:/data/db
        environment:
            MONGO_INITDB_DATABASE: mydb
            MONGODB_AUTH: yes
            MONGODB_ADMIN_USER: root
            MONGODB_ADMIN_PASS: honterus
    mariadb:
        image: 'mariadb:10'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sail-mariadb:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: [CMD, redis-cli, ping]
            retries: 3
            timeout: 5s
    memcached:
        image: 'memcached:alpine'
        ports:
            - '${FORWARD_MEMCACHED_PORT:-11211}:11211'
        networks:
            - sail
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'sail-meilisearch:/meili_data'
        networks:
            - sail
        healthcheck:
            test: [CMD, wget, '--no-verbose', '--spider', 'http://localhost:7700/health']
            retries: 3
            timeout: 5s
#    minio:
#        image: 'minio/minio:latest'
#        ports:
#            - '${FORWARD_MINIO_PORT:-9001}:9001'
#            - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
#        environment:
#            MINIO_ROOT_USER: sail
#            MINIO_ROOT_PASSWORD: password
#        volumes:
#            - 'sail-minio:/data/minio'
#        networks:
#            - sail
#        command: 'minio server /data/minio --console-address ":8900" --address ":9001"'
#        healthcheck:
#            test:
#                - CMD
#                - curl
#                - '-f'
#                - 'http://localhost:9000/minio/health/live'
#            retries: 3
#            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
#    selenium:
#        image: selenium/standalone-chrome
#        extra_hosts:
#            - 'host.docker.internal:host-gateway'
#        volumes:
#            - '/dev/shm:/dev/shm'
#        networks:
#            - sail
    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        environment:
            SOKETI_DEBUG: '${SOKETI_DEBUG:-1}'
            SOKETI_METRICS_SERVER_PORT: '9601'
            SOKETI_DEFAULT_APP_ID: '${PUSHER_APP_ID}'
            SOKETI_DEFAULT_APP_KEY: '${PUSHER_APP_KEY}'
            SOKETI_DEFAULT_APP_SECRET: '${PUSHER_APP_SECRET}'
        ports:
            - '${PUSHER_PORT:-6001}:6001'
            - '${PUSHER_METRICS_PORT:-9601}:9601'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mariadb:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
    sail-minio:
        driver: local
    sail-cassandra:
        driver: local
    mongo-data:
        driver: local
